name: Despliegue en GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2

      - name: Configurar variables de entorno
        run: |
          echo "API_KEY=${{ secrets.API_KEY }}" >> $GITHUB_ENV
          echo "CLIENT_ID=${{ secrets.CLIENT_ID }}" >> $GITHUB_ENV

      - name: Instalar dependencias
        run: npm install

      - name: Desplegar en GitHub Pages
        run: npm run build
        env:
          API_KEY: ${{ secrets.API_KEY }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}

      - name: Configurar Google Sheets API
        run: |
          gcloud auth activate-service-account --key-file=service-account-key.json
          gcloud config set project YOUR_PROJECT_ID
          gcloud auth configure-docker
